### ISSUE TITLE
项目完整版源码

### ISSUE THREAD

**Issue by royzhao1978** [tmpbook/django-with-vuejs#11]
你好，目前在代码库中的代码只是框架，不知道能否提供项目完整版源码？

**Comment by tmpbook** [comment]
@royzhao1978 我只是演示了如何结合，并没有什么项目呀

**Comment by Xmas118** [comment]
Where is you 'dist' folder?

**Comment by tmpbook** [comment]
@Xmas118 just run `npm run build` in frontend directory

**Comment by Xmas118** [comment]
So Must execute 'npm run dev' every time to see the results?

**Comment by Xmas118** [comment]
TEMPLATES.DIRS 's value is dist path So must execute 'run build' every time to see the results?

**Comment by tmpbook** [comment]
@Xmas118 you can execute `run dev` to see the results，if you want exchange data with django, you can use the full path like `http://127.0.0.1:8000/query` just like this below:

```javascript
if (process.env.NODE_ENV === 'production') {
    base = '';
} else {
    base = 'http://localhost:8000';
}
```

**Comment by Xmas118** [comment]
i'll try. thx
