### ISSUE TITLE
how to handle django login page from vuejs ?

### ISSUE THREAD

**Issue by gagansuntle** [tmpbook/django-with-vuejs#13]
hi,
    I followed your project structure. I would like to know how we can use allauth templates from vuejs components ?

**Comment by tmpbook** [comment]
if you want use the django auth, you can try the [DRF](http://www.django-rest-framework.org/), because the vuejs usually use the json  to transport data
```
Content-Type:application/json
```

**Comment by tmpbook** [comment]
@gagansuntle Now you can use the DRF auth view.
