### ISSUE TITLE
啥反应也没有.. 浏览器也没报错

### ISSUE THREAD

**Issue by 625781186** [tmpbook/django-with-vuejs#16]
![image](https://user-images.githubusercontent.com/30521429/48707772-754ce780-ec3b-11e8-9096-215ef90ef6ea.png)

**Comment by tmpbook** [comment]
@625781186 搞定了？什么问题？

**Comment by 625781186** [comment]
> @625781186 搞定了？什么问题？

url路径写错了..哈哈
