### ISSUE TITLE
python: can't open file 'manage': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by frankforp** [tmpbook/django-with-vuejs#18]
Hi,

After install the third-lib in requirements.txt and run the the server In the directory where 
The message "python: can't open file 'manage': [Errno 2] No such file or directory" will be shown in cmd.

Could you please tell me how could i resolve this problem?

Thanks,
Peng

**Comment by frankforp** [comment]
Sorry, 
the command should be " python manage.py createsuperuser"
I close it.

**Comment by tmpbook** [comment]
> Sorry,
> the command should be " python manage.py createsuperuser"
> I close it.

thanks, i fix README.md either

**Comment by frankforp** [comment]
> > Sorry,
> > the command should be " python manage.py createsuperuser"
> > I close it.
> 
> thanks, i fix README.md either

You are welcome!
