### ISSUE TITLE
代码和知乎专栏里的代码不一样，以哪个为准？

### ISSUE THREAD

**Issue by zaxlct** [tmpbook/django-with-vuejs#2]
-`settings.py` 代码和知乎专栏里的代码不一样，以哪个为准？

我按照知乎专栏的步骤一步一步来的，运行 vue 和 django 后提示：
![image](https://cloud.githubusercontent.com/assets/14342431/23328676/ad1abec4-fb62-11e6-994e-97beb87ef447.png)

我前端项目里，`static` 目录是空的，不知道为什么，是不是因为这个原因？
![image](https://cloud.githubusercontent.com/assets/14342431/23328678/deb9fb3e-fb62-11e6-929c-2c4b34495a26.png)

麻烦了 :)

**Comment by tmpbook** [comment]
``` python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        **'DIRS': ['frontend/dist']**,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

双星号包起来的就是寻找index.html的路径配置，我专栏文章是有的，你看看你的路径，对照一下

**Comment by guoyucheng** [comment]
npm run build出现异常
没有找到frontend/build/build.js'， 这个是什么问题

**Comment by tmpbook** [comment]
@guoyucheng 你需要按知乎里面的步骤操作，传到git的代码，会有部分被 .eslintignore 忽略掉 [看这里](https://github.com/tmpbook/django-with-vuejs/commit/2d67eb4361398c4914d8dc5b6a825c6b4d708809#diff-63a4f99244cbd32b2730a372cab12124)
