### ISSUE TITLE
设置 STATICFILED_DIRS 仍然找不到静态文件

### ISSUE THREAD

**Issue by Nataila** [tmpbook/django-with-vuejs#5]
我webpack之后的文件在 app/dist/static/build.js
index.html 里面引入是用的 <scirpt src='./build.js'></script>
在django的settings里面设置了
`  STATICFILES_DIRS = [
      os.path.join(BASE_DIR, 'app/dist/static')
  ]`
INSTALLED_APP里面也加了 `app`

但是运行的时候，仍然找不到build.js
是不是需要再index.html引入build.js的时候仍然需要使用{% static '' %}?

**Comment by tmpbook** [comment]
@Nataila 找不到的时候你在浏览器看它访问的路径是什么，然后改一下`STATICFILES_DIRS `，再看一下访问静态文件的路径，你就会理解了，希望对你有帮助。
