### ISSUE TITLE
npm run build 出错

### ISSUE THREAD

**Issue by muyang** [tmpbook/django-with-vuejs#6]
错误

(env) D:\MU\Projects\django-with-vuejs\my_project\frontend>npm run build

> frontend@1.0.0 build D:\MU\Projects\django-with-vuejs\my_project\frontend
> node build/build.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\MU\Projects\django-with-vuejs\my_project\frontend\build\build.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! frontend@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@1.0.0 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\MU\Projects\django-with-vuejs\my_project\frontend\npm-debug.log

(env) D:\MU\Projects\django-with-vuejs\my_project\frontend>

**Comment by tmpbook** [comment]
@muyang 你需要自己使用vue-cli来创建前端的开发环境，git上传的是没有配置文件的，你看错误第一行，它找不到build.js那个配置文件，我本地有的，但是你没有

**Comment by yangzi129** [comment]
能提供一下build目录文件么 ， 想跑着学习一下，不然跑不起来
