### ISSUE TITLE
<div id="app">不会自动注入

### ISSUE THREAD

**Issue by yokinzzz** [tmpbook/django-with-vuejs#8]
在运行了python manage.py runserver后，vue组件并不会注入到<div id="app"> tag中，在localhost:8080/demo中页面显示为空白，同时/admin中能够正常显示

**Comment by tmpbook** [comment]
js和css加载成功了吗，看看配置





高远
Simple is better.
在2017年06月23日 09:03，Yokin 写道：

在运行了python manage.py runserver后，vue组件并不会注入到

tag中，在localhost:8080/demo中页面显示为空白，同时/admin中能够正常显示

**Comment by yokinzzz** [comment]
js加载成功了，问题是router里的index.js中hello.vue的位置有错，应该在上级目录
thx
